jobs:
- name: qa
  plan:
  - get: emr-cluster-broker
    trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'emr-cluster-broker/terraform/deploy/app'
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'emr-cluster-broker/terraform/deploy/app'
    params:
      TF_WORKSPACE: qa
